version: '3' # versão do yaml

services: # representam os containers
  ideedutech-backend: # nome do serviço
    image: postgres # imagem que o docker irá se basear para criar o container
    environment: # variáveis de ambiente
      POSTGRES_PASSWORD: 'postgres'
    container_name: ideedutech-backend # nome do container

    ports: # portas para acessar o container
      - '8081:5432'
    volumes: # onde serão armazenadas as informações do banco
      - .docker/dbdata:/var/lib/postgresql/data