name: CI_IDEEDUTEC

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v2

     - name: Setup Nestjs
       uses: actions/setup-node@v2
       with:
        node-version: 14.18.1

     - name: Install Dependecies
       run: yarn 

     - name: Build
       run: yarn build 
        
     - name: Publish
       uses: nogsantos/scp-deploy@master
       with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
